Repository mujtaba7vals/workflow_engine_app, pull requests merged in 2020-10, with the labels that each got.

#23 Initial watchers setup
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/controllers/issues_controller.rb
  app/controllers/watchers_controller.rb
  app/mailers/application_mailer.rb
  app/mailers/issue_mailer.rb
  app/mailers/watcher_mailer.rb
  app/models/ability.rb
  app/models/issue.rb
  app/models/user.rb
  app/models/watcher.rb
  app/views/issue_mailer/status_changed.html.erb
  app/views/issues/_issue_body.html.erb
  app/views/issues/show.html.erb
  app/views/issues/update_status.js.erb
  app/views/watcher_mailer/stopped_watching_issue.html.erb
  app/views/watcher_mailer/watching_issue_now.html.erb
  app/views/watchers/_watch_links.html.erb
  app/views/watchers/_watchers_list.html.erb
  app/views/watchers/administrate.html.erb
  app/views/watchers/update.js.erb
  bin/delayed_job
  config/application.rb
  config/environments/development.rb
  config/initializers/pagy.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200925060015_create_delayed_jobs.rb
Labels: Ready to Merge

#49 Login/Singup forms added
  app/assets/stylesheets/application.scss
  app/controllers/companies_controller.rb
  app/controllers/issues_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/helpers/application_helper.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/_companies_link.html.erb
  app/views/home/_company_link.html.erb
  app/views/home/sign_in.html.erb
  app/views/invites/confirm_request.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_signed_in_user_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/users/new.html.erb
  config/locales/en.yml
Labels: Peer review in progress, Ready for Peer Review

#44 Feature/change role
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/views/users/_index_table.html.erb
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/make_owner_page.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: Ready for Peer Review

#50 Add role with invitation
  app/controllers/issues_controller.rb
  app/mailers/invite_mailer.rb
  app/views/invites/confirm_request.html.erb
  app/views/invites/new.html.erb
  app/views/layouts/_navbar.html.erb
Labels: Ready for Peer Review

#54 Consistency
  app/assets/stylesheets/application.scss
  app/controllers/projects_controller.rb
  app/helpers/application_helper.rb
  app/helpers/home_helper.rb
  app/models/user.rb
  app/views/companies/index.html.erb
  app/views/issues/_issues_table.html.erb
  app/views/projects/_project_teams_list.html.erb
  app/views/projects/_project_users_list.html.erb
  app/views/projects/index.html.erb
  app/views/projects/show.html.erb
  app/views/teams/_teams_table.html.erb
  app/views/teams/show.html.erb
  app/views/users/_index_table.html.erb
  config/locales/en.yml
  db/schema.rb
Labels: Comments Pending

#55 css added
  app/assets/stylesheets/application.scss
Labels: Ready for Peer Review

#53 Search functionality
  app/assets/stylesheets/application.scss
  app/controllers/search_controller.rb
  app/controllers/users_controller.rb
  app/models/company.rb
  app/views/companies/index.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/_signed_in_user_navbar.html.erb
  app/views/search/_search_form.html.erb
  app/views/search/search.html.erb
  config/locales/en.yml
  config/routes.rb
  db/schema.rb
Labels: Ready for Peer Review
