Repository mujtaba7vals/workflow_engine_app, pull requests merged in 2020-09, with the labels that each got.

#2 Feature/add bootstrap
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.scss
  app/controllers/home_controller.rb
  app/helpers/home_helper.rb
  app/javascript/packs/application.js
  app/views/home/index.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  config/database.yml
  config/routes.rb
  config/webpack/environment.js
  package.json
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
  yarn.lock
Labels: Comments Pending

#4 Devise
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/company.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  config/database.yml
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200907121405_devise_create_users.rb
  db/migrate/20200907133359_devise_create_companies.rb
  db/migrate/20200908055721_add_company_id_to_users.rb
  db/schema.rb
Labels: Comments Pending

#5 Issues
  Gemfile
  Gemfile.lock
  app/models/comment.rb
  app/models/issue.rb
  app/models/project.rb
  app/models/user.rb
  app/models/watcher.rb
  config/database.yml
  db/migrate/20200909055926_create_teams.rb
  db/migrate/20200909060037_create_projects.rb
  db/migrate/20200909060131_create_project_teams.rb
  db/migrate/20200909061949_create_team_users.rb
  db/migrate/20200909062111_create_project_users.rb
  db/migrate/20200909072302_create_issues.rb
  db/migrate/20200909072537_create_comments.rb
  db/migrate/20200909083144_create_watchers.rb
Labels: Ready to Merge

#11 Added buttons in navbar for sign in, sign up and sign out
  app/views/layouts/_navbar.html.erb
  config/locales/en.yml
Labels: Ready to Merge

#8 Devise
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/javascript/packs/application.js
  app/models/company.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/mailer.html.erb
  config/application.rb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/en.yml
  db/migrate/20200907121405_devise_create_users.rb
  db/migrate/20200907133359_create_companies.rb
  db/migrate/20200907133359_devise_create_companies.rb
  db/migrate/20200908055721_add_company_id_to_users.rb
  db/schema.rb
Labels: Ready to Merge

#14 Resolve Syntax in en.yml
  app/models/company.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  config/locales/en.yml
Labels: Ready to Merge

#10 Pagy added
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/users/index.html.erb
  config/database.yml
  config/initializers/pagy.rb
Labels: PR is ready for final review

#15 Feature/ui
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/sb-admin-2.min.css
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/helpers/home_helper.rb
  app/models/ability.rb
  app/models/project.rb
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_normal_user_navbar.html.erb
  app/views/layouts/_signed_in_user_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/projects/_form.html.erb
  app/views/projects/_new_team_for_project.html.erb
  app/views/projects/_new_user_for_project.html.erb
  app/views/projects/_project_teams_list.html.erb
  app/views/projects/_project_users_list.html.erb
  app/views/projects/index.html.erb
  app/views/projects/show.html.erb
  app/views/teams/_form.html.erb
  app/views/teams/_new_member_to_team.html.erb
  app/views/teams/index.html.erb
  app/views/teams/show.html.erb
  config/locales/en.yml
Labels: Ready to Merge

#17 Feature/add other users
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/invitations/new.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/devise/registrations/new.html.erb
  app/views/users/index.html.erb
  app/views/users/new.html.erb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200922054158_add_invitable_to_users.rb
  db/migrate/20200922063121_add_default_to_user_column.rb
  db/migrate/20200922071405_change_default_of_role.rb
  db/schema.rb
Labels: Ready for Peer Review

#20 Pagination Added on Projects and Teams Index Pages with custom color …
  app/assets/stylesheets/application.scss
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/users_controller.rb
  app/models/company.rb
  app/views/projects/index.html.erb
  app/views/teams/index.html.erb
  app/views/users/index.html.erb
  config/initializers/pagy.rb
  db/schema.rb
Labels: Ready to Merge

#12 Feature/multitenancy
  Gemfile
  app/controllers/application_controller.rb
  app/controllers/companies_controller.rb
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/models/ability.rb
  app/models/application_record.rb
  app/models/company.rb
  app/models/project.rb
  app/models/user.rb
  app/views/companies/index.html.erb
  app/views/home/_companies_link.html.erb
  app/views/home/_company_link.html.erb
  app/views/home/about.html.erb
  app/views/home/contact_us.html.erb
  app/views/home/index.html.erb
  app/views/home/sign_in.html.erb
  app/views/home/user_companies.js.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_normal_user_navbar.html.erb
  app/views/layouts/_signed_in_user_navbar.html.erb
  config/environments/development.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200916113620_reindex_users_by_email_and_company_id.rb
Labels: Ready for Peer Review

#7 Feature/issue crud and views
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/issues_controller.rb
  app/helpers/application_helper.rb
  app/helpers/comments_helper.rb
  app/helpers/issues_helper.rb
  app/models/ability.rb
  app/models/application_record.rb
  app/models/comment.rb
  app/models/company.rb
  app/models/issue.rb
  app/models/project.rb
  app/models/user.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_form.html.erb
  app/views/comments/_comments.html.erb
  app/views/comments/_edit_comment_form.html.erb
  app/views/comments/create.js.erb
  app/views/comments/destroy.js.erb
  app/views/comments/edit.js.erb
  app/views/comments/show.js.erb
  app/views/issues/_issue_body.html.erb
  app/views/issues/_issue_form_internal.html.erb
  app/views/issues/_show_badges.html.erb
  app/views/issues/_status_change_form.html.erb
  app/views/issues/edit.html.erb
  app/views/issues/new.html.erb
  app/views/issues/show.html.erb
  app/views/issues/update_status.js.erb
  app/views/layouts/_errors.html.erb
  config/initializers/pagy.rb
  config/locales/en.yml
  config/routes.rb
  db/schema.rb
Labels: Ready for Peer Review

#16 Feature/document
  app/controllers/issues_controller.rb
  app/models/issue.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/issues/_issue_form_internal.html.erb
  app/views/issues/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20200918092018_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: PR is ready for final review

#13 Feature/user sequence number
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/models/user.rb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200917081538_add_sequence_num_to_users.rb
Labels: Ready to Merge

#21 Issues Table Added
  app/assets/stylesheets/application.scss
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/helpers/home_helper.rb
  app/models/user.rb
  app/views/layouts/_signed_in_user_navbar.html.erb
  app/views/projects/_project_teams_list.html.erb
  app/views/projects/_project_users_list.html.erb
  app/views/projects/edit.js.erb
  app/views/projects/index.html.erb
  app/views/projects/new.js.erb
  app/views/projects/new_team_for_project.js.erb
  app/views/projects/new_user_for_project.js.erb
  app/views/projects/show.html.erb
  app/views/teams/edit.js.erb
  app/views/teams/index.html.erb
  app/views/teams/new.js.erb
  app/views/teams/new_user_for_team.js.erb
  app/views/teams/show.html.erb
  config/locales/en.yml
  db/schema.rb
Labels: Ready to Merge

#18 Bradcrumbs Added
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/views/layouts/_navbar.html.erb
  config/locales/en.yml
Labels: Ready to Merge

#25 Removed invitable gem and made the necessary modifications
  Gemfile
  Gemfile.lock
  app/models/ability.rb
  app/models/user.rb
  app/views/users/index.html.erb
  config/initializers/devise.rb
  config/routes.rb
Labels: Ready to Merge

#22 UI incorporation in document
  app/assets/javascripts/application.js
  app/controllers/application_controller.rb
  app/controllers/issues_controller.rb
  app/views/issues/_issue_form_internal.html.erb
  app/views/issues/show.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: Ready to Merge

#24 Trying to add Sequence No on Project Modal
  Gemfile
  Gemfile.lock
  app/assets/images/about_1.png
  app/assets/images/landing_1.png
  app/assets/stylesheets/landing-page-style.css
  app/controllers/home_controller.rb
  app/controllers/issues_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/helpers/application_helper.rb
  app/models/ability.rb
  app/models/project.rb
  app/models/team.rb
  app/views/companies/index.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_normal_user_navbar.html.erb
  app/views/layouts/_signed_in_user_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/projects/_form.html.erb
  app/views/projects/show.html.erb
  app/views/teams/_form.html.erb
  config/locales/en.yml
  db/migrate/20200925073808_add_sequence_num_to_projects.rb
  db/migrate/20200925115515_add_sequence_num_to_teams.rb
Labels: Ready to Merge

#29 Sign up reloading
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
Labels: Ready to Merge

#26 Added feature
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
  config/routes.rb
Labels: Ready to Merge

#32 Added redirection if there is only one company for the user email
  app/views/home/sign_in.html.erb
  app/views/home/user_companies.js.erb
Labels: Ready for Peer Review

#31 Solved subdomain issue
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/shared/_links.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
Labels: Ready for Peer Review

#33 Moved the redirection to controller
  app/controllers/home_controller.rb
  app/views/home/user_companies.js.erb
Labels: Ready to Merge

#34 Users Link Added on Dashboard
  app/helpers/application_helper.rb
Labels: PR is ready for final review

#35 Assignee through project members
  app/models/project.rb
  app/models/user.rb
Labels: Ready to Merge

#30 Project Filters Added
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/models/ability.rb
  app/models/project.rb
  app/models/team.rb
  app/views/layouts/application.html.erb
  app/views/projects/_index_table.html.erb
  app/views/projects/filters.js.erb
  app/views/projects/index.html.erb
  app/views/teams/index.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: Ready to Merge

#36 Errors Handled
  app/controllers/application_controller.rb
  app/views/layouts/record_not_found.html.erb
  config/locales/en.yml
  config/routes.rb
  public/404.html
  public/404.html.erb
Labels: Ready to Merge

#37 Feature/bread crums
  app/assets/stylesheets/application.scss
  app/controllers/companies_controller.rb
  app/controllers/issues_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/users_controller.rb
  app/views/layouts/_navbar.html.erb
Labels: Ready to Merge

#39 Edit
  app/controllers/users_controller.rb
Labels: PR is ready for final review

#28 Hotfix/user sign up
  app/controllers/invites_controller.rb
  app/mailers/application_mailer.rb
  app/mailers/invite_mailer.rb
  app/models/ability.rb
  app/models/company.rb
  app/models/invite.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/invite_mailer/new_user_invite.html.erb
  app/views/invites/confirm_request.html.erb
  app/views/invites/create_staff_user.html.erb
  app/views/invites/new.html.erb
  app/views/users/index.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200922054158_add_invitable_to_users.rb
  db/migrate/20200925083154_create_invites.rb
  db/schema.rb
  test/mailers/invite_mailer_test.rb
  test/mailers/previews/invite_mailer_preview.rb
  test/models/invite_test.rb
Labels: PR is ready for final review

#27 Feature/list view of users
  app/controllers/invites_controller.rb
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/views/users/_index_table.html.erb
  app/views/users/filters.js.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: Ready to Merge

#38 Add filter and index view to issues
  app/assets/stylesheets/application.scss
  app/controllers/issues_controller.rb
  app/controllers/projects_controller.rb
  app/helpers/application_helper.rb
  app/helpers/issues_helper.rb
  app/models/issue.rb
  app/views/issues/_issues_list_view.html.erb
  app/views/issues/_issues_table.html.erb
  app/views/issues/all.html.erb
  app/views/issues/all.js.erb
  config/locales/en.yml
  config/routes.rb
  db/schema.rb
Labels: Ready for Peer Review

#41 Feature/delete user
  app/assets/javascripts/application.js
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/views/layouts/_normal_user_navbar.html.erb
  app/views/users/_index_table.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: Ready for Peer Review

#42 Feature/link index page to invite users
  app/controllers/invites_controller.rb
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
Labels: Ready for Peer Review

#43 Added an ability for staff to access issues
  app/models/ability.rb
Labels: Ready for Peer Review

#40 AJAX pagination added and some updation in forms in list of project a…
  app/assets/stylesheets/application.scss
  app/controllers/projects_controller.rb
  app/controllers/teams_controller.rb
  app/views/layouts/_form_errors.html.erb
  app/views/projects/_form.html.erb
  app/views/projects/_index_table.html.erb
  app/views/projects/_issues_list.html.erb
  app/views/projects/_new_team_for_project.html.erb
  app/views/projects/_new_user_for_project.html.erb
  app/views/projects/_project_teams_list.html.erb
  app/views/projects/_project_users_list.html.erb
  app/views/projects/create.js.erb
  app/views/projects/filters.js.erb
  app/views/projects/index.html.erb
  app/views/projects/show.html.erb
  app/views/projects/show.js.erb
  app/views/projects/update.js.erb
  app/views/teams/_form.html.erb
  app/views/teams/_new_member_to_team.html.erb
  app/views/teams/_teams_table.html.erb
  app/views/teams/create.js.erb
  app/views/teams/index.html.erb
  app/views/teams/index.js.erb
  app/views/teams/show.html.erb
  app/views/teams/update.js.erb
  config/locales/en.yml
  db/schema.rb
Labels: Comments Pending

#46 Passed email to company login form as param
  app/controllers/home_controller.rb
  app/views/devise/sessions/new.html.erb
Labels: Ready for Peer Review

#47 Redirected back on fallback and notifications for issue actions
  app/controllers/issues_controller.rb
  config/locales/en.yml
Labels: Ready for Peer Review

#48 Fixed dependency issues
  app/models/project.rb
  app/models/team.rb
  app/models/user.rb
Labels: Ready for Peer Review
